name: qsafevault
description: cross-platform password manager
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cryptography: ^2.7.0
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  synchronized: ^3.4.0
  bitsdojo_window: ^0.1.6
  uuid: ^4.5.1
  pointycastle: ^3.7.3
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.3
  http: ^1.2.2
  flutter_webrtc: ^1.2.0
  archive: ^3.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.22.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true

  assets:
    - public/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "public/logo.png"
  android: true
  ios: true
